spring:
  mail:
    host: smtp.163.com
    username: royster61@163.com
    password: SOZUOHNHSELFISQR
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /
    #   阿里云服务器
    host: 47.120.40.130
    port: 5672
  security:
    jwt:
      key: royster61
      expire: 7
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itbaima